Update git workflows for new dev branch

diff --git a/.github/workflows/node-build-test.yml b/.github/workflows/node-build-test.yml
--- a/.github/workflows/node-build-test.yml
+++ b/.github/workflows/node-build-test.yml
@@ -5,13 +5,12 @@ name: Node.js CI
 
 on:
   push:
-    branches: [ "main" ]
+    branches: ["main", "dev"]
   pull_request:
-    branches: [ "main" ]
+    branches: ["main", "dev"]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     strategy:
@@ -20,19 +19,19 @@ jobs:
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
-    - uses: actions/checkout@v4
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v4
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-    - run: npm ci
-    - run: |
-        if ! npm run prettier:check --if-present; then
-          # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions
-          echo "::warning prettier:check failed, formatting may be bad, or .prettierignore may need adjustment"
-          false
-        fi
-      continue-on-error: true # at least until the failures are eradicated
-    - run: npm run build --workspaces --if-present
-    - run: npm test
+      - uses: actions/checkout@v4
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: "npm"
+      - run: npm ci
+      - run: |
+          if ! npm run prettier:check --if-present; then
+            # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions
+            echo "::warning prettier:check failed, formatting may be bad, or .prettierignore may need adjustment"
+            false
+          fi
+        continue-on-error: true # at least until the failures are eradicated
+      - run: npm run build --workspaces --if-present
+      - run: npm test
